# Generated by Django 4.0.2 on 2025-04-15 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_user_order_alter_movie_actors_alter_movie_genres_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='cinemahall',
            constraint=models.UniqueConstraint(fields=('rows', 'seats_in_row'), name='unique_rows_seats_in_row'),
        ),
    ]
