# Generated by Django 4.0.2 on 2025-04-15 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0003_cinemahall_unique_rows_seats_in_row'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='ticket',
            constraint=models.UniqueConstraint(fields=('row', 'seat'), name='unique_seat_row'),
        ),
    ]
