# Generated by Django 4.0.2 on 2025-04-15 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0004_ticket_unique_seat_row'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='ticket',
            name='unique_seat_row',
        ),
    ]
