# Generated by Django 4.0.2 on 2025-04-15 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0005_remove_ticket_unique_seat_row'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='cinemahall',
            name='unique_rows_seats_in_row',
        ),
    ]
